/*
 * SSD_prog.c
 *
 *  Created on: Feb 3, 2016
 *      Author: m.mamdooh
 */

#include "type.h"
#include"SSD_config.h"
#include"SSD_interface.h"
#include"DIO-interface.h"
#if (SSD_u8DISPMAXIDX==SSD_u8DISP1)
u8 const SSD_Disp[1][7]={SSD_u8DISP1SEGA,SSD_u8DISP1SEGB,SSD_u8DISP1SEGC,SSD_u8DISP1SEGD,SSD_u8DISP1SEGE,SSD_u8DISP1SEGF,SSD_u8DISP1SEGG};
u8 const SSD_CommPins[]={SSD_u8DISP1COM};

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP2)
u8 SSD_Disp[2][7]=
{SSD_u8DISP1SEGA,SSD_u8DISP1SEGB,SSD_u8DISP1SEGC,SSD_u8DISP1SEGD,SSD_u8DISP1SEGE,SSD_u8DISP1SEGF,SSD_u8DISP1SEGG,
SSD_u8DISP2SEGA,SSD_u8DISP2SEGB,SSD_u8DISP2SEGC,SSD_u8DISP2SEGD,SSD_u8DISP2SEGE,SSD_u8DISP2SEGF,SSD_u8DISP2SEGG};
u8 SSD_CommPins[]={SSD_u8DISP1COM,SSD_u8DISP2COM};

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP3)
u8 SSD_Disp[3][7]=
{SSD_u8DISP1SEGA,SSD_u8DISP1SEGB,SSD_u8DISP1SEGC,SSD_u8DISP1SEGD,SSD_u8DISP1SEGE,SSD_u8DISP1SEGF,SSD_u8DISP1SEGG,
SSD_u8DISP2SEGA,SSD_u8DISP2SEGB,SSD_u8DISP2SEGC,SSD_u8DISP2SEGD,SSD_u8DISP2SEGE,SSD_u8DISP2SEGF,SSD_u8DISP2SEGG,
SSD_u8DISP3SEGA,SSD_u8DISP3SEGB,SSD_u8DISP3SEGC,SSD_u8DISP3SEGD,SSD_u8DISP3SEGE,SSD_u8DISP3SEGF,SSD_u8DISP3SEGG};
u8 SSD_CommPins[]={SSD_u8DISP1COM,SSD_u8DISP2COM,SSD_u8DISP3COM};

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP4)
u8 SSD_Disp[4][7]=
{SSD_u8DISP1SEGA,SSD_u8DISP1SEGB,SSD_u8DISP1SEGC,SSD_u8DISP1SEGD,SSD_u8DISP1SEGE,SSD_u8DISP1SEGF,SSD_u8DISP1SEGG,
SSD_u8DISP2SEGA,SSD_u8DISP2SEGB,SSD_u8DISP2SEGC,SSD_u8DISP2SEGD,SSD_u8DISP2SEGE,SSD_u8DISP2SEGF,SSD_u8DISP2SEGG,
SSD_u8DISP3SEGA,SSD_u8DISP3SEGB,SSD_u8DISP3SEGC,SSD_u8DISP3SEGD,SSD_u8DISP3SEGE,SSD_u8DISP3SEGF,SSD_u8DISP3SEGG,
SSD_u8DISP4SEGA,SSD_u8DISP4SEGB,SSD_u8DISP4SEGC,SSD_u8DISP4SEGD,SSD_u8DISP4SEGE,SSD_u8DISP4SEGF,SSD_u8DISP4SEGG};

u8 SSD_CommPins[]={SSD_u8DISP1COM,SSD_u8DISP2COM,SSD_u8DISP3COM,SSD_u8DISP4COM};

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP5)
u8 SSD_Disp[5][7]=
{SSD_u8DISP1SEGA,SSD_u8DISP1SEGB,SSD_u8DISP1SEGC,SSD_u8DISP1SEGD,SSD_u8DISP1SEGE,SSD_u8DISP1SEGF,SSD_u8DISP1SEGG,
SSD_u8DISP2SEGA,SSD_u8DISP2SEGB,SSD_u8DISP2SEGC,SSD_u8DISP2SEGD,SSD_u8DISP2SEGE,SSD_u8DISP2SEGF,SSD_u8DISP2SEGG,
SSD_u8DISP3SEGA,SSD_u8DISP3SEGB,SSD_u8DISP3SEGC,SSD_u8DISP3SEGD,SSD_u8DISP3SEGE,SSD_u8DISP3SEGF,SSD_u8DISP3SEGG,
SSD_u8DISP4SEGA,SSD_u8DISP4SEGB,SSD_u8DISP4SEGC,SSD_u8DISP4SEGD,SSD_u8DISP4SEGE,SSD_u8DISP4SEGF,SSD_u8DISP4SEGG,
SSD_u8DISP5SEGA,SSD_u8DISP5SEGB,SSD_u8DISP5SEGC,SSD_u8DISP5SEGD,SSD_u8DISP5SEGE,SSD_u8DISP5SEGF,SSD_u8DISP5SEGG};

u8 SSD_CommPins[]={SSD_u8DISP1COM,SSD_u8DISP2COM,SSD_u8DISP3COM,SSD_u8DISP4COM,SSD_u8DISP5COM};

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP6)
u8 SSD_Disp[6][7]=
{SSD_u8DISP1SEGA,SSD_u8DISP1SEGB,SSD_u8DISP1SEGC,SSD_u8DISP1SEGD,SSD_u8DISP1SEGE,SSD_u8DISP1SEGF,SSD_u8DISP1SEGG,
SSD_u8DISP2SEGA,SSD_u8DISP2SEGB,SSD_u8DISP2SEGC,SSD_u8DISP2SEGD,SSD_u8DISP2SEGE,SSD_u8DISP2SEGF,SSD_u8DISP2SEGG,
SSD_u8DISP3SEGA,SSD_u8DISP3SEGB,SSD_u8DISP3SEGC,SSD_u8DISP3SEGD,SSD_u8DISP3SEGE,SSD_u8DISP3SEGF,SSD_u8DISP3SEGG,
SSD_u8DISP4SEGA,SSD_u8DISP4SEGB,SSD_u8DISP4SEGC,SSD_u8DISP4SEGD,SSD_u8DISP4SEGE,SSD_u8DISP4SEGF,SSD_u8DISP4SEGG,
SSD_u8DISP5SEGA,SSD_u8DISP5SEGB,SSD_u8DISP5SEGC,SSD_u8DISP5SEGD,SSD_u8DISP5SEGE,SSD_u8DISP5SEGF,SSD_u8DISP5SEGG,
SSD_u8DISP6SEGA,SSD_u8DISP6SEGB,SSD_u8DISP6SEGC,SSD_u8DISP6SEGD,SSD_u8DISP6SEGE,SSD_u8DISP6SEGF,SSD_u8DISP6SEGG};

u8 SSD_CommPins[]={SSD_u8DISP1COM,SSD_u8DISP2COM,SSD_u8DISP3COM,SSD_u8DISP4COM,SSD_u8DISP5COM,SSD_u8DISP6COM};

#endif

#if(SSD_u8CATHODE)
u8 SSD_NumsBinary[10][7]=
{DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,
DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8LOW,DIO_u8LOW,DIO_u8LOW,
DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8HIGH,
DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8LOW,DIO_u8HIGH,
DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,
DIO_u8HIGH,DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,
DIO_u8HIGH,DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,
DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8LOW,DIO_u8LOW,DIO_u8LOW,
DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,
DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8HIGH,DIO_u8LOW,DIO_u8HIGH,DIO_u8HIGH};
#else
u8 SSD_NumsBinary[10][7]=
{~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,
~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8LOW,~DIO_u8LOW,~DIO_u8LOW,
~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8HIGH,
~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8LOW,~DIO_u8HIGH,
~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,
~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,
~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,
~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8LOW,~DIO_u8LOW,~DIO_u8LOW,
~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,
~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8HIGH,~DIO_u8LOW,~DIO_u8HIGH,~DIO_u8HIGH};

#endif

u8 SSD_Check[2]={ok,error};
u8 SSD_DispVal[6] ;

extern void SSD_voidInit(void)
{

#if (SSD_u8DISPMAXIDX==SSD_u8DISP1)
     /*comment!: initialize Display state*/
     DIO_u8WritePinVal(SSD_u8DISP1COM ,SSD_u8DISP1_INITSTATE);

     /*comment!: initialize Display NUmber*/
     SSD_u8Display(SSD_u8DISP1,SSD_u8DISP1_INITVAL);

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP2)
     /*comment!: initialize Display state*/
     DIO_u8WritePinVal(SSD_u8DISP1COM ,SSD_u8DISP1_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP2COM ,SSD_u8DISP2_INITSTATE);

     /*comment!: initialize Display NUmber*/
     SSD_u8Display(SSD_u8DISP1,SSD_u8DISP1_INITVAL);
     SSD_u8Display(SSD_u8DISP2,SSD_u8DISP2_INITVAL);

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP3)
     /*comment!: initialize Display state*/
     DIO_u8WritePinVal(SSD_u8DISP1COM ,SSD_u8DISP1_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP2COM ,SSD_u8DISP2_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP3COM ,SSD_u8DISP3_INITSTATE);

     /*comment!: initialize Display NUmber*/
     SSD_u8Display(SSD_u8DISP1,SSD_u8DISP1_INITVAL);
     SSD_u8Display(SSD_u8DISP2,SSD_u8DISP2_INITVAL);
     SSD_u8Display(SSD_u8DISP3,SSD_u8DISP3_INITVAL);

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP4)
     /*comment!: initialize Display state*/
     DIO_u8WritePinVal(SSD_u8DISP1COM ,SSD_u8DISP1_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP2COM ,SSD_u8DISP2_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP3COM ,SSD_u8DISP3_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP4COM ,SSD_u8DISP4_INITSTATE);

     /*comment!: initialize Display NUmber*/
     SSD_u8Display(SSD_u8DISP1,SSD_u8DISP1_INITVAL);
     SSD_u8Display(SSD_u8DISP2,SSD_u8DISP2_INITVAL);
     SSD_u8Display(SSD_u8DISP3,SSD_u8DISP3_INITVAL);
     SSD_u8Display(SSD_u8DISP4,SSD_u8DISP4_INITVAL);

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP5)
     /*comment!: initialize Display state*/
     DIO_u8WritePinVal(SSD_u8DISP1COM ,SSD_u8DISP1_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP2COM ,SSD_u8DISP2_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP3COM ,SSD_u8DISP3_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP4COM ,SSD_u8DISP4_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP5COM ,SSD_u8DISP5_INITSTATE);

     /*comment!: initialize Display NUmber*/
     SSD_u8Display(SSD_u8DISP1,SSD_u8DISP1_INITVAL);
     SSD_u8Display(SSD_u8DISP2,SSD_u8DISP2_INITVAL);
     SSD_u8Display(SSD_u8DISP3,SSD_u8DISP3_INITVAL);
     SSD_u8Display(SSD_u8DISP4,SSD_u8DISP4_INITVAL);
     SSD_u8Display(SSD_u8DISP5,SSD_u8DISP5_INITVAL);

#elif (SSD_u8DISPMAXIDX==SSD_u8DISP6)
     /*comment!: initialize Display state*/
     DIO_u8WritePinVal(SSD_u8DISP1COM ,SSD_u8DISP1_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP2COM ,SSD_u8DISP2_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP3COM ,SSD_u8DISP3_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP4COM ,SSD_u8DISP4_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP5COM ,SSD_u8DISP5_INITSTATE);
     DIO_u8WritePinVal(SSD_u8DISP6COM ,SSD_u8DISP6_INITSTATE);

     /*comment!: initialize Display NUmber*/
     SSD_u8Display(SSD_u8DISP1,SSD_u8DISP1_INITVAL);
     SSD_u8Display(SSD_u8DISP2,SSD_u8DISP2_INITVAL);
     SSD_u8Display(SSD_u8DISP3,SSD_u8DISP3_INITVAL);
     SSD_u8Display(SSD_u8DISP4,SSD_u8DISP4_INITVAL);
     SSD_u8Display(SSD_u8DISP5,SSD_u8DISP5_INITVAL);
     SSD_u8Display(SSD_u8DISP5,SSD_u8DISP6_INITVAL);
#endif



}

u8 SSD_u8Display(u8 Copy_u8DispIdx,u8 Copy_u8DisVal)
{

	u8 Local_u8LoopCount;
	SSD_DispVal[Copy_u8DispIdx]=Copy_u8DisVal;

		for(Local_u8LoopCount=0;Local_u8LoopCount<7;Local_u8LoopCount++)
		{
		DIO_u8WritePinVal(SSD_Disp[Copy_u8DispIdx][Local_u8LoopCount],SSD_NumsBinary[Copy_u8DisVal][Local_u8LoopCount]);
		}


	return  SSD_Check[Copy_u8DispIdx < 6]  ;
}


extern u8 SSD_u8TurnOn(u8 Copy_u8DispIdx)
{

	DIO_u8WritePinVal(SSD_CommPins[Copy_u8DispIdx] ,SSD_u8ONSTATE);
	return  SSD_Check[Copy_u8DispIdx < 6]  ;
}

extern u8 SSD_u8TurnOff(u8 Copy_u8DispIdx)
{

	DIO_u8WritePinVal(SSD_CommPins[Copy_u8DispIdx] ,SSD_u8OFFSTATE);


	return  SSD_Check[Copy_u8DispIdx < 6]  ;
}

extern u8 SSD_u8GetVal(u8 Copy_u8DispIdx,u8* Copy_u8DisVal)
{
	* Copy_u8DisVal=SSD_DispVal[Copy_u8DispIdx];
	return  SSD_Check[Copy_u8DispIdx < 6]  ;
}
